### ISSUE TITLE
Possible typo?

### ISSUE THREAD

**Issue by g-berthiaume** [gingerBill/gingerBill.org#1]
In [memory-allocation-strategies-001/thinking-about-allocation](https://www.gingerbill.org/article/2019/02/01/memory-allocation-strategies-001/#thinking-about-allocation)
> In C, <code>malloc</code> et al is a solution to this domain of problems.

Not sure what you mean by "et al".

Thanks for your articles on memory management. 
Great read, so far.

**Comment by gingerBill** [comment]
"et al" means "and others" in Latin.

**Comment by g-berthiaume** [comment]
haha well, it looks like you're teaching me more than memory management. :^)

Sorry for the noise in your issues. 
Mea culpa and have a good day.
